---
- name: configure clusterrolebinding deployment directory
  file: path={{ item }} state=directory
  with_items:
    - /var/lib/k8s-deploy/kubelet_clusterrolebinding
  tags:
    - k8s
    - kubelet

- name: copy kubelet_clusterrolebinding.yaml
  template: src={{ item }}.j2 dest=/var/lib/k8s-deploy/kubelet_clusterrolebinding/{{ item }}
  with_items:
    - clusterrolebinding_for_kubelet_certificate.yaml
  tags:
    - k8s
    - kubelet

- name: deploy kubelet_clusterrolebinding
  command: kubectl apply -f /var/lib/k8s-deploy/kubelet_clusterrolebinding/{{ item }}
  with_items:
    - clusterrolebinding_for_kubelet_certificate.yaml
  tags:
    - k8s
    - kubelet

- name: undeploy kubelet_clusterrolebinding
  command: kubectl delete -f /var/lib/k8s-deploy/kubelet_clusterrolebinding/{{ item }}
  with_items:
    - clusterrolebinding_for_kubelet_certificate.yaml
  tags:
    - uninstall
    - uninstall-k8s
    - uninstall-kubelet

- name: remove kubelet_clusterrolebinding yaml
  file: 
    path="/var/lib/k8s-deploy/kubelet_clusterrolebinding"
    state="absent"
  tags:
    - uninstall
    - uninstall-k8s
    - uninstall-kubelet
