---
- hosts: [hosts]
  roles:
  - base
  - chrony
  - docker

- hosts: [etcds]
  roles:
  - etcd

- hosts: [k8s]
  roles:
  - kube-deps

- hosts: [masters]
  roles:
  - kube-apiserver

- hosts: [haproxy]
  roles:
  - haproxy

- hosts: [masters]
  roles:
  - kube-controller-manager
  - kube-scheduler
  - kubectl
  - kube-clusterrolebinding

- hosts: [nodes]
  roles:
  - kubelet
  - kube-proxy



