---
# - hosts: [kubectl-run-host]
#   roles:
#     - calico
#     - kube-dns
#     - kube-heapster
#     - kube-dashboard
#     - ceph

- hosts: [hosts]
  roles:
  - base
  - chrony
  - docker

- hosts: [etcds]
  roles:
  - etcd

- hosts: [masters]
  roles:
  - kube-apiserver

- hosts: [haproxy]
  roles:
  - haproxy

- hosts: [masters]
  roles:
  - kube-controller-manager
  - kube-scheduler
  - kubectl

- hosts: [nodes]
  roles:
  - kubelet
  - kube-proxy

- hosts: [k8s]
  roles:
  - kube-deps

