---
- name: Install ceph-common
  package: 
    name: ceph-common
    state: present
  when: install_ceph_common
  tags: 
    - k8s
    - node
    - kubelet

- name: Create kubelet log directory
  file: 
    path: "{{ item }}"
    state: "directory"
  with_items:
    - "{{ kube_log_dir }}/kubelet"
  tags: 
    - k8s
    - node
    - kubelet

- name: Configure kubelet service account key/pub
  copy: 
      src: "certs/keys/{{ item }}"
      dest: "{{ kube_ssl_dir }}/{{ item }}"
      mode: 0644
  with_items:
    - ca.crt
    - ca.key
    - kubelet.crt
    - kubelet.key
  tags: 
    - k8s
    - node
    - cert
    - kubelet

- name: Create bootstrap_kubeconfig file for kubelet
  template: 
    src: "bootstrap_kubeconfig.j2"
    dest: "/var/lib/kubernetes/bootstrap_kubeconfig"
  notify: Systemd Reload
  tags: 
    - k8s
    - node
    - kubelet


