---
# tasks file for k8s-node
- include_tasks: configure.yaml
  tags:
    - k8s
    - node
    - kubelet

- include_tasks: kubelet.yaml
  tags:
    - k8s
    - node
    - kubelet

- include_tasks: uninstall.yaml
  tags:
    - uninstall
    - uninstall-k8s
    - uninstall-kubelet
