---
- name: stop service kubelet
  service:
    name: kubelet.service
    state: stopped
  tags:
    - uninstall
    - uninstall-k8s
    - uninstall-kubelet

- name: remove kubelet related config
  file:
    path: "/usr/lib/systemd/system/kubelet.service"
    state: "absent"
  tags:
    - uninstall
    - uninstall-k8s
    - uninstall-kubelet