---
- name: Create kube-apiserver log directory
  file:
    path: "{{ item }}"
    state: "directory"
  with_items:
    - "{{ kube_log_dir }}/kube-apiserver"
  tags:
    - k8s
    - master
    - apiserver

- name: Configure kube-apiserver serviceaccount key/pub
  copy: 
      src: "certs/keys/{{ item }}"
      dest: "{{ kube_ssl_dir }}/{{ item }}"
      mode: 0644
  with_items:
    - ca.crt
    - ca.key
    - admin.crt
    - admin.key
    - serviceaccount.key
    - serviceaccount.crt
    - server.crt
    - server.key
  tags: 
    - k8s
    - master
    - cert
    - apiserver
