apiVersion: v1
kind: Pod
metadata:
  name: csirbd-demo-pod
spec:
  containers:
  - image: registry.docker-cn.com/library/centos:7
    name: test-container
    command:
      - "/bin/sh"
    args:
      - "-c"
      - "sleep 360000"
    volumeMounts:
      - name: mypvc
        mountPath: "/mnt/ceph/csi_rbd"
  volumes:
   - name: mypvc
     persistentVolumeClaim:
       claimName: rbd-pvc-csi
       readOnly: false

