---
- name: 'include os-specific vars'
  include_vars: "{{ansible_os_family | lower }}.yml"
  tags:
    - 'chrony'

- include_tasks: "install.yml"
  tags:
    - 'chrony'
- include_tasks: "configure.yml"
  tags:
    - 'chrony'
- include_tasks: "service.yml"
  tags:
    - 'chrony'
