---
apiVersion: v1
kind: Pod
metadata:
  name: centos7
  labels:
    app: centos7
spec:
  containers:
  - image: registry.docker-cn.com/library/centos:7
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Always