---
apiVersion: v1
kind: Pod
metadata:
  name: centos7
  labels:
    app: centos7
spec:
  containers:
  - image: zdq0394/centos:7a
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Always