---
- name: stop firewalld
  service: name=firewalld.service enabled=False state=stopped
  tags:
    - base

- name: set selinux permissive
  selinux:
    policy: targeted
    state: permissive
  tags:
    - base

- name: set selinux disabled
  selinux:
    state: disabled
  tags:
    - base