---
- name: stop service kube-scheduler
  service:
    name: kube-scheduler.service
    state: stopped
  tags:
    - uninstall
    - uninstall-k8s
    - uninstall-kube-scheduler

- name: remove kube-scheduler related config
  file:
    path: "/usr/lib/systemd/system/kube-scheduler.service"
    state: "absent"
  tags:
    - uninstall
    - uninstall-k8s
    - uninstall-kube-scheduler