---
- name: Create kube-controller-manager log directory
  file:
    path: "{{ item }}"
    state: "directory"
  with_items:
    - "{{ kube_log_dir }}/kube-controller-manager"
  tags:
    - k8s
    - master
    - controller-manager