---
- name: stop service kube-controller-manager
  service:
    name: kube-controller-manager.service
    state: stopped
  tags:
    - uninstall
    - uninstall-k8s
    - uninstall-kube-controller-manager

- name: remove kube-controller-manager related config
  file:
    path: "/usr/lib/systemd/system/kube-controller-manager.service"
    state: "absent"
  tags:
    - uninstall
    - uninstall-k8s
    - uninstall-kube-controller-manager