- name: Create kubernetes related directory
  file: path={{ item }} state=directory
  with_items:
    - /etc/kubernetes/ssl
  tags:
    - k8s
    - master
    - node
    - cert
    - kube-deps

- name: Configure serviceaccount key/pub
  copy: 
      src: "certs/keys/{{ item }}"
      dest: "{{ kube_ssl_dir }}/{{ item }}"
      mode: 0644
  with_items:
    - ca.crt
    - ca.key
    - serviceaccount.key
    - serviceaccount.crt
    - server.crt
    - server.key
    - admin.crt
    - admin.key
    - kube-controller-manager.crt
    - kube-controller-manager.key
    - kube-scheduler.crt
    - kube-scheduler.key
  tags: 
    - k8s
    - master
    - node
    - cert
    - kube-deps
